"""Sidecar mock APIsec server for E2E tests.

Routes by the `application_id` segment of the URL:
  /v1/applications/<scenario>/instances/<x>/scan          (POST init)
  /v1/applications/<scenario>/instances/<x>/scans/<id>    (GET poll)

Listens on HTTPS :8443 using cert/key under MOCK_CERT_DIR (default /certs).
The cert is generated by the workflow before starting this server.

Counters persist per (scenario, route) for stateful scenarios like flaky-502.
"""
import json
import os
import ssl
import sys
import threading
from collections import defaultdict
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse

CERT_DIR = os.environ.get("MOCK_CERT_DIR", "/certs")
PORT = int(os.environ.get("MOCK_PORT", "8443"))

CRITICAL_FINDING = {
    "method": "GET",
    "resource": "/api/users/{id}",
    "scanFindings": [{
        "testResult": {"cvssScore": 9.5, "cvssQualifier": "Critical"},
        "testDetails": {"categoryName": "Auth", "categoryTestName": "BOLA"},
        "testStatus": {"description": "Authorization check missing on user resource"},
    }],
}

NULL_SCORE_FINDING = {
    "method": "GET",
    "resource": "/api/x",
    "scanFindings": [{
        "testResult": {"cvssScore": None, "cvssQualifier": "Critical"},
        "testDetails": {"categoryName": "Drift", "categoryTestName": "NullScore"},
        "testStatus": {"description": "API returned null score"},
    }],
}


class MockHandler(BaseHTTPRequestHandler):
    counters = defaultdict(int)

    def log_message(self, *a, **kw):
        return

    def _send_json(self, code, payload):
        body = json.dumps(payload).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _send_raw(self, code, ctype, body):
        if isinstance(body, str):
            body = body.encode()
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _route(self):
        parts = urlparse(self.path).path.strip("/").split("/")
        # parts: v1, applications, <scenario>, instances, <x>, scan|scans, [scan_id]
        if len(parts) < 6:
            return None, None
        scenario = parts[2]
        verb = parts[5]  # 'scan' (init) or 'scans' (poll list/by-id)
        return scenario, verb

    def do_POST(self):
        length = int(self.headers.get("Content-Length") or 0)
        if length:
            self.rfile.read(length)
        self.handle_request(is_init=True)

    def do_GET(self):
        self.handle_request(is_init=False)

    def handle_request(self, is_init):
        scenario, _ = self._route()

        # Init scenarios
        if is_init:
            if scenario == "init-no-scanid":
                return self._send_json(200, {"status": "Queued"})
            if scenario == "init-non-json":
                return self._send_raw(200, "text/html", "<html>not json</html>")
            # All other scenarios: init succeeds normally
            return self._send_json(200, {"scanId": "scan-123", "status": "Queued"})

        # Poll scenarios
        if scenario == "happy-1-critical-fail":
            return self._send_json(200, {
                "scanId": "scan-123", "status": "Complete",
                "vulnerabilities": [CRITICAL_FINDING],
            })
        if scenario == "happy-1-critical-pass":
            return self._send_json(200, {
                "scanId": "scan-123", "status": "Complete",
                "vulnerabilities": [CRITICAL_FINDING],
            })
        if scenario == "zero-vulns":
            return self._send_json(200, {
                "scanId": "scan-123", "status": "Complete",
                "vulnerabilities": [],
            })
        if scenario == "failed-status":
            return self._send_json(200, {
                "scanId": "scan-123", "status": "Failed",
            })
        if scenario == "poll-404":
            return self._send_json(404, {"error": "scan not found"})
        if scenario == "flaky-502-recovers":
            MockHandler.counters[scenario] += 1
            if MockHandler.counters[scenario] <= 2:
                return self._send_raw(502, "text/html", "<html>Bad Gateway</html>")
            return self._send_json(200, {
                "scanId": "scan-123", "status": "Complete",
                "vulnerabilities": [CRITICAL_FINDING],
            })
        if scenario == "null-cvss":
            return self._send_json(200, {
                "scanId": "scan-123", "status": "Complete",
                "vulnerabilities": [NULL_SCORE_FINDING],
            })
        # Default
        return self._send_json(200, {"scanId": "scan-123", "status": "Complete", "vulnerabilities": []})


def main():
    cert = os.path.join(CERT_DIR, "cert.pem")
    key = os.path.join(CERT_DIR, "key.pem")
    if not (os.path.exists(cert) and os.path.exists(key)):
        print(f"Missing cert/key under {CERT_DIR}", file=sys.stderr)
        sys.exit(1)

    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.load_cert_chain(cert, key)

    httpd = ThreadingHTTPServer(("0.0.0.0", PORT), MockHandler)
    httpd.socket = ctx.wrap_socket(httpd.socket, server_side=True)
    print(f"mock-apisec listening on https://0.0.0.0:{PORT}", flush=True)
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
