name: APIsec Latest Scan Gate
on:
  pull_request:
  push:
    branches: [main]

jobs:
  apisec-gate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: Gavin-Hensley/apisec-cicd-latest-fetch@v0.2.3
        with:
          application_id: ${{ secrets.APISEC_APPLICATION_ID }}
          instance_id: ${{ secrets.APISEC_INSTANCE_ID }}
          access_token: ${{ secrets.APISEC_ACCESS_TOKEN }}
          fail_on_severity_threshold: '8'
          fail_on_error_threshold: '0'
          print_summary: 'true'